---
  openapi: 3.0.0
  info:
    version: 0.1.0
    title: Backpacker API
  servers:
    - url: http://localhost:3000/
  security:
    - basicAuth: []
  paths:
    /users:
      get:
        description: Get all users or the users matching the criteria specified as query parameters
        tags:
          - user
        parameters:
          - in: query
            name: email
            description: user email, required for anyone but admins
            schema:
              type: string
        responses:
          200:
            description: All Users / the users matching the search criteria
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: Users have to provide an email address.
          500:
            description: Server Error
      post:
        description: Create user
        tags:
          - user
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
                required:
                  - firstName
                  - lastName
        responses:
          200:
            description: 'The user with the googleId already exists (see response body)'
          201:
            description: 'Created User'
          400:
            description: 'Bad Request'
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: >
                           Forbidden: The google id in the request body has
                           to match the user id the token was created for.
          500:
            description: 'Server Error'
    /users/{userId}:
      parameters:
        - in: path
          name: userId
          description: user id
          required: true
          schema:
            $ref: '#/components/schemas/ObjectId'
      get:
        description: Get user
        tags:
          - user
        responses:
          200:
            description: The User
          400:
            description: Bad Request
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: 'Forbidden: Users can only access their own profile'
          500:
            description: Server Error
      patch:
        description: Update user
        tags:
          - user
        requestBody:
          required: true
          content:
            application/merge-patch+json:
              schema:
                $ref: '#/components/schemas/User'
        responses:
          204:
            description: User Updated
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: 'Forbidden: Users can only patch their own profile'
          400:
            description: Bad Request
          500:
            description: Server Error
      delete:
        description: Delete user
        tags:
          - user
        responses:
          204:
            description: User Deleted
          400:
            description: Bad Request
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: 'Forbidden: Users can only delete their own profile'
          500:
            description: Server Error
    /users/{userId}/friends:
      parameters:
        - in: path
          name: userId
          description: user id for currently logged in user
          required: true
          schema:
            $ref: '#/components/schemas/ObjectId'
      get:
        description: Get user's friends'
        tags:
          - user
        responses:
          200:
            description: User's Friends
          400:
            description: 'Bad Request'
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: 'Forbidden: Users can only access their own friends'
          500:
            description: 'Server Error'
    /users/{userId}/friends/{friendId}:
      parameters:
        - in: path
          name: userId
          description: user id
          required: true
          schema:
            $ref: '#/components/schemas/ObjectId'
        - in: path
          name: friendId
          description: friend's user id
          required: true
          schema:
            $ref: '#/components/schemas/ObjectId'
      put:
        description: Add friend
        tags:
          - user
        responses:
          204:
            description: Friend Added
          400:
            description: Bad Request
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: 'Forbidden: Users can only add friends to themselves'
          500:
            description: Server Error
      delete:
        description: Remove friend
        tags:
          - user
        responses:
          204:
            description: Friend Removed
          400:
            description: Bad Request
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: 'Forbidden: Users can only remove their own friends'
          500:
            description: Server Error
    /users/{userId}/avatar:
      parameters:
        - in: path
          name: userId
          description: user id
          required: true
          schema:
            $ref: '#/components/schemas/ObjectId'      
      put:
        description: Upload avatar
        tags:
          - user
        requestBody:
          content:
            multipart/form-data:
              schema:
                properties:
                  avatar:
                    type: string
                    format: binary
        responses:
          202:
            description: Avatar Uploaded
          400:
            description: Bad Request
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: 'Forbidden: Users can only upload an avatar to their own profile'
          500:
            description: Server Error
      delete:
        description: Remove Avatar
        tags:
          - user
        responses:
          204:
            description: Avatar Removed
          400:
            description: Bad Request
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: 'Forbidden: Users can only remove their own avatar'
          500:
            description: Server Error
    /locations:
      get:
        description: Get the locations of the users specified as query parameters
        tags:
          - location
        parameters:
          - in: query
            name: users
            description: the users that added the location
            required: true
            schema:
              type: array
              items:
                type: string
          - in: query
            name: googleId
            description: google id of the location
            required: false
            schema:
              type: string
        responses:
          200:
            description: Locations
          400:
            description: Bad Request
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: 'Forbidden: The user can only request locations of their own friends'
          500:
            description: Server Error
      post:
        description: Add new location
        tags:
          - location
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
                required:
                  - user
                  - googleId
                  - coordinates
                  - city
                  - country
        responses:
          201:
            description: Created Location
          400:
            description: Bad Request
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: Forbidden: Users can only create locations for themselves
          500:
            description: Server Error
              
                
    /locations/{id}:
      parameters:
        - in: path
          name: id
          description: location id
          required: true
          schema:
            $ref: '#/components/schemas/ObjectId'
      patch:
        description: Update location
        tags:
          - location
        requestBody:
          required: true
          content:
            application/merge-patch+json:
              schema:
                $ref: '#/components/schemas/Location'
        responses:
          204:
            description: Location Updated
          400:
            description: Bad Request
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: 'Forbidden: Users can only patch their own locations'
          500:
            description: Server Error
      delete:
        description: Delete Location
        tags:
          - location
        responses:
          204:
            description: User removed
          400:
            description: Bad Request
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: 'Forbidden: Users can only delete their own locations'
          500:
            description: Server Error
    /locations/{id}/images:
      parameters:
        - in: path
          name: id
          description: location id
          required: true
          schema:
            $ref: '#/components/schemas/ObjectId'
      post:
        description: Upload location images
        tags:
          - location
        requestBody:
          content:
            multipart/form-data:
              schema:
                properties:
                  images:
                    type: array
                    items:
                      type: string
                      format: binary
        responses:
          202:
            description: Image Upload Started
          400:
            description: Bad Request
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: 'Forbidden: Users can only add images to their own locations'
          500:
            description: Server Error
    /location/{locationId}/images/{imageId}:
      parameters:
        - in: path
          name: locationId
          description: location id
          required: true
          schema:
            $ref: '#/components/schemas/ObjectId'
        - in: path
          name: imageId
          description: image id
          required: true
          schema:
            $ref: '#/components/schemas/ObjectId'
      delete:
        description: Delete Image
        tags:
          - location
        responses:
          204:
            description: Image Deleted
          400:
            description: Bad Request
          401:
            description: 'Unauthorized: Authentication failed'
          403:
            description: 'Forbidden: Users can only remove images from their own locations'
          500:
            description: Server Error
  components:
    securitySchemes:
      basicAuth:
        type: http
        scheme: basic
    schemas:
      User:
        type: object
        properties:
          googleId:
            type: string
            minLength: 1
          firstName:
            type: string
            minLength: 1
          lastName:
            type: string
            minLength: 1
          email:
            type: string
      Location:
        type: object
        properties:
          name:
            type: string
          user:
            type: string
            minLength: 24
            maxLength: 24
          googleId:
            type: string
          favorite:
            type: boolean
          description:
            type: string
          coordinates:
            type: array
            items: 
              type: string
              minItems: 2
              maxItems: 2
          city:
            type: string
          country:
            type: string
      ObjectId:
        type: string
        minLength: 24
        maxLength: 24
  tags:
    - name: user
    - name: location
